// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1070
package controlplane

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "html/template"

func layout(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(data.Lang)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 7, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" dir=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(data.Dir)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 7, Col: 40}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" data-theme=\"light\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 11, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " · Report Maker</title><script src=\"/static/htmx.min.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("<script>"+themeScript+"</script>").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("<style>"+styleCSS+"</style>").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.ExtraScript {
			templ_7745c5c3_Err = templ.Raw("<script>"+passkeyJS+"</script>").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</head><body><header class=\"topbar\"><div class=\"wrap\"><div class=\"topbar-inner\"><a class=\"brand\" href=\"/\"><span class=\"brand-mark\">RM</span> <span><span class=\"brand-name\">Report Maker</span><div class=\"brand-sub\">Offline engineering reports</div></span></a><nav class=\"main-nav\" aria-label=\"Primary\" id=\"main-nav\"><a href=\"/#product\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.JourneyProduct)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 31, Col: 53}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</a> <a href=\"/pricing\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.NavPricing)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 32, Col: 48}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</a> <a href=\"/download\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.NavDownload)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 33, Col: 50}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</a> <a href=\"/support\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.FooterSupport)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 34, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</a> <a href=\"/login\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.NavSignIn)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 35, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</a> <a class=\"nav-cta\" href=\"/pricing\">Buy licence</a> <button type=\"button\" class=\"btn ghost\" id=\"theme-toggle\" aria-label=\"Toggle theme\" title=\"Toggle light/dark\" style=\"padding:7px 10px;font-size:14px\">◐</button><div style=\"display:inline-flex;gap:6px;margin-inline-start:4px\"><a href=\"?lang=en\" class=\"btn ghost\" style=\"padding:6px 8px;font-size:12px\" aria-label=\"English\">EN</a> <a href=\"?lang=fa\" class=\"btn ghost\" style=\"padding:6px 8px;font-size:12px\" aria-label=\"فارسی\">FA</a></div></nav><button type=\"button\" class=\"mobile-toggle btn secondary\" id=\"mobile-toggle\" aria-label=\"Menu\" style=\"padding:7px 10px\">☰</button></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.ShowJourney {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div class=\"wrap\" style=\"padding-top:14px\"><ol class=\"journey\"><li")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.JourneyStep == 1 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " class=\"active\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.JourneyProduct)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 54, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</li><li")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.JourneyStep == 2 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, " class=\"active\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.JourneyPricing)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 59, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</li><li")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.JourneyStep == 3 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, " class=\"active\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.JourneyPay)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 64, Col: 29}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</li><li")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.JourneyStep == 4 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, " class=\"active\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.JourneySignIn)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 69, Col: 32}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</li><li")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.JourneyStep == 5 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, " class=\"active\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var14 string
			templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.JourneyDownloads)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 74, Col: 35}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "</li></ol></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "<div id=\"toast\" role=\"status\" aria-live=\"polite\" style=\"position:fixed;bottom:18px;inset-inline-start:50%;transform:translateX(-50%);background:var(--ink);color:#fff;padding:10px 16px;border-radius:8px;font-size:13px;display:none;z-index:50;max-width:90vw;box-shadow:0 8px 32px rgba(0,0,0,.2)\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("<script>"+qolScript+"</script>").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "<footer class=\"site-footer\"><div class=\"wrap\"><div class=\"footer-grid\"><div class=\"footer-col\"><a class=\"brand\" href=\"/\" style=\"margin-bottom:10px\"><span class=\"brand-mark\">RM</span> <span><span class=\"brand-name\">Report Maker</span></span></a><p style=\"font-size:14px;color:var(--muted);max-width:320px\">Offline-first report builder for vibration engineers. Import SP3 and CSV locally, edit in the desktop app, export polished DOCX — no project data leaves your machine.</p><p style=\"margin-top:10px\"><a href=\"/pricing\" class=\"btn\" style=\"padding:8px 14px;font-size:13px\">Get a licence</a></p></div><div class=\"footer-col\"><h4>Product</h4><a href=\"/#product\">How it works</a> <a href=\"/#features\">Features</a> <a href=\"/pricing\">Pricing</a> <a href=\"/download\">Download</a> <a href=\"/offline-use\">Offline use</a></div><div class=\"footer-col\"><h4>Support</h4><a href=\"/support\">Contact support</a> <a href=\"/install\">Install &amp; verify</a> <a href=\"/faq\">FAQ</a> <a href=\"/account\">Account</a> <a href=\"/account/purchases\">Purchases</a></div><div class=\"footer-col\"><h4>Legal</h4><a href=\"/privacy\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var15 string
		templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.FooterPrivacy)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 110, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "</a> <a href=\"/refund\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 string
		templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.FooterRefund)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 111, Col: 49}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "</a> <a href=\"/support\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.FooterSupport)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 112, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "</a> <a href=\"/offline-use\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var18 string
		templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.FooterOffline)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 113, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "</a> <a href=\"/install\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var19 string
		templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.FooterInstall)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 114, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "</a> <a href=\"/faq\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var20 string
		templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.JoinStringErrs(data.Copy.FooterFAQ)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 115, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var20))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</a></div></div><div class=\"footer-bottom\"><span>© Report Maker — Desktop stays offline. Licences are perpetual per major version.</span> <span>Domestic payments via ZarinPal · <a href=\"/support\">support</a> replies with order ID</span></div></div></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func csrfInputTempl(token string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var21 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var21 == nil {
			templ_7745c5c3_Var21 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "<input type=\"hidden\" name=\"csrf_token\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var22 string
		templ_7745c5c3_Var22, templ_7745c5c3_Err = templ.ResolveAttributeValue(token)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `layout.templ`, Line: 129, Col: 53}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var22)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// styleCSS includes light and dark theme tokens. Default light; dark via [data-theme="dark"].
var styleCSS = `:root{--ink:#0f1f2e;--ink2:#304055;--muted:#5f6f85;--line:#dde5ee;--panel:#f3f5f7;--panel2:#eef2f5;--accent:#c4451a;--accent-hover:#a83a14;--accent-soft:#fdf0eb;--ok:#0a7a42;--warn:#8a6100;--radius:10px;--radius-sm:8px;--max:1120px}
[data-theme="dark"]{--ink:#e8eef5;--ink2:#b8c6d9;--muted:#8a9ab2;--line:#243447;--panel:#162433;--panel2:#1c2f45;--accent:#e85d2a;--accent-hover:#ff6b35;--accent-soft:#2a1c16}
[data-theme="dark"] body{background:#0d1a2a;color:var(--ink)}
[data-theme="dark"] .topbar{background:rgba(13,26,42,.96);border-color:var(--line)}
[data-theme="dark"] .hero-card, [data-theme="dark"] .feat, [data-theme="dark"] .step, [data-theme="dark"] .plan-card, [data-theme="dark"] .auth-section, [data-theme="dark"] article.purchase, [data-theme="dark"] article.download, [data-theme="dark"] .faq-item, [data-theme="dark"] .compare{background:#132238;border-color:var(--line)}
[data-theme="dark"] .hero-card-head, [data-theme="dark"] .plan-head, [data-theme="dark"] .compare-head, [data-theme="dark"] .site-footer{background:#162433}
[data-theme="dark"] .doc-preview{background:linear-gradient(180deg,#132238 0%,#0d1a2a 100%)}
[data-theme="dark"] .doc-sheet{background:#1c2f45;border-color:var(--line)}
[data-theme="dark"] .field input, [data-theme="dark"] .field select, [data-theme="dark"] .field textarea{background:#1c2f45;border-color:var(--line);color:var(--ink)}
[data-theme="dark"] code{background:#1c2f45;border-color:var(--line)}

*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{margin:0;font:16px/1.55 system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);background:#fff;-webkit-font-smoothing:antialiased}
a{color:var(--accent);text-decoration:none}
a:hover{text-decoration:underline}
h1,h2,h3{font-family:Georgia,"Times New Roman",serif;letter-spacing:-.02em;line-height:1.15;color:var(--ink)}
h1{font-size:42px;margin:0 0 .5rem}
h2{font-size:26px;margin:0 0 .6rem}
h3{font-size:18px;margin:0 0 .35rem}
p{margin:.5rem 0;color:var(--ink2)}
small{color:var(--muted)}
.wrap{max-width:var(--max);margin:0 auto;padding:0 24px}
.topbar{position:sticky;top:0;z-index:20;background:rgba(255,255,255,.96);backdrop-filter:saturate(1.2) blur(8px);border-bottom:1px solid var(--line)}
.topbar-inner{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px 0}
.brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:var(--ink)}
.brand-mark{width:32px;height:32px;border:1px solid var(--ink);display:grid;place-items:center;font-weight:800;font-size:13px;letter-spacing:.04em;background:var(--ink);color:#fff}
.brand-name{font-weight:800;letter-spacing:-.02em;font-size:18px}
.brand-sub{font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);margin-top:1px}
.main-nav{display:flex;gap:22px;align-items:center;font-size:14px;font-weight:500}
.main-nav a{color:var(--ink2);text-decoration:none}
.main-nav a:hover{color:var(--ink)}
.nav-cta{display:inline-flex;align-items:center;justify-content:center;padding:9px 16px;background:var(--accent);color:#fff;border-radius:var(--radius-sm);font-weight:650;font-size:14px;border:1px solid var(--accent);text-decoration:none}
.nav-cta:hover{background:var(--accent-hover);border-color:var(--accent-hover);text-decoration:none;color:#fff}
.mobile-toggle{display:none}
@media(max-width:860px){.main-nav{gap:14px;flex-wrap:wrap}.mobile-toggle{display:inline-flex}}
.hero{display:grid;grid-template-columns:1.15fr .85fr;gap:40px;padding:36px 0 28px;align-items:center}
.hero-copy p.lead{font-size:18px;line-height:1.5;color:var(--ink2);max-width:560px}
.kicker{display:inline-flex;align-items:center;gap:8px;font-size:12px;letter-spacing:.06em;text-transform:uppercase;font-weight:700;color:var(--muted);margin-bottom:12px}
.kicker i{width:8px;height:8px;background:var(--accent);display:inline-block;border-radius:50%}
.cta-row{display:flex;gap:12px;flex-wrap:wrap;margin:18px 0 14px}
html[dir="rtl"] .cta-row{flex-direction:row-reverse}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:11px 18px;border-radius:8px;font-weight:650;font-size:15px;border:1px solid var(--accent);background:var(--accent);color:#fff;text-decoration:none;cursor:pointer;line-height:1}
.btn:hover{background:var(--accent-hover);border-color:var(--accent-hover);color:#fff;text-decoration:none}
.btn.secondary{background:#fff;color:var(--ink);border-color:var(--line)}
.btn.secondary:hover{background:var(--panel);border-color:var(--line)}
.btn.ghost{background:transparent;border-color:transparent;color:var(--ink2)}
.meta-row{display:flex;gap:18px;flex-wrap:wrap;font-size:13px;color:var(--muted);margin-top:8px}
.meta-row span{display:inline-flex;gap:6px;align-items:center}
.hero-card{border:1px solid var(--line);border-radius:12px;overflow:hidden;background:#fff;box-shadow:0 8px 32px rgba(15,31,46,.08)}
.hero-card-head{padding:14px 16px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;background:var(--panel)}
.hero-card-head strong{font-size:13px}
.hero-card-head small{font-size:12px}
.doc-preview{padding:16px;background:linear-gradient(180deg,#fff 0%,#f7f8f9 100%)}
.doc-sheet{border:1px solid var(--line);background:#fff;border-radius:8px;padding:16px}
.doc-line{height:8px;background:var(--panel2);border-radius:4px;margin:8px 0}
.doc-line.w60{width:60%}.doc-line.w80{width:80%}.doc-line.w40{width:40%}
.doc-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}
.doc-cell{border:1px solid var(--line);border-radius:6px;padding:10px;background:var(--panel)}
.doc-cell b{font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:var(--muted)}
.doc-cell p{font-size:13px;margin:4px 0 0;color:var(--ink)}
.trustbar{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:16px;border:1px solid var(--line);border-radius:10px;background:var(--panel);margin:18px 0 0}
.trustbar b{font-size:20px;display:block;line-height:1}
.trustbar span{font-size:12px;color:var(--muted);letter-spacing:.04em;text-transform:uppercase;font-weight:600}
.journey{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 22px;padding:0;list-style:none;font-size:13px;color:var(--muted)}
.journey li{padding:6px 12px;border-radius:999px;background:var(--panel);border:1px solid var(--line);font-weight:550}
.journey li.active{background:var(--ink);color:#fff;border-color:var(--ink)}
html[dir="rtl"] .journey{flex-direction:row-reverse}
.section{padding:32px 0;border-top:1px solid var(--line)}
.section.noborder{border-top:0}
.section-head{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:18px;flex-wrap:wrap}
.section-head p{max-width:540px;color:var(--muted);margin:0}
.feature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}
@media(max-width:860px){.feature-grid{grid-template-columns:1fr 1fr}.hero{grid-template-columns:1fr}}
@media(max-width:560px){.feature-grid{grid-template-columns:1fr}.hero h1{font-size:34px}}
.feat{border:1px solid var(--line);border-radius:10px;padding:16px;background:#fff}
.feat-icon{width:36px;height:36px;border:1px solid var(--line);border-radius:8px;display:grid;place-items:center;background:var(--panel);margin-bottom:10px;color:var(--ink)}
.feat h3{font-family:system-ui,sans-serif;font-size:15px;margin:0 0 6px;letter-spacing:-.01em}
.feat p{font-size:14px;line-height:1.5;margin:0;color:var(--muted)}
.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;position:relative}
@media(max-width:700px){.steps{grid-template-columns:1fr}}
.step{border:1px solid var(--line);border-radius:10px;padding:18px;background:#fff;position:relative}
.step-num{width:28px;height:28px;border-radius:50%;background:var(--ink);color:#fff;display:grid;place-items:center;font-size:13px;font-weight:700;margin-bottom:10px}
.compare{border:1px solid var(--line);border-radius:10px;overflow:hidden}
.compare-row{display:grid;grid-template-columns:1.1fr 1fr 1fr;gap:0;font-size:14px}
.compare-row>div{padding:12px 14px;border-bottom:1px solid var(--line)}
.compare-head{background:var(--panel);font-weight:700;font-size:12px;letter-spacing:.06em;text-transform:uppercase;color:var(--muted)}
.compare-row>div:first-child{font-weight:600;color:var(--ink)}
.tick{color:var(--ok);font-weight:700}
.pricing-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:20px;align-items:start}
@media(max-width:860px){.pricing-grid{grid-template-columns:1fr}}
.plan-card{border:1px solid var(--ink);border-radius:12px;overflow:hidden;background:#fff}
.plan-head{padding:18px 20px;border-bottom:1px solid var(--line);background:var(--panel)}
.plan-head h2{margin:0;font-size:22px}
.plan-price{font-size:28px;font-weight:800;letter-spacing:-.03em;margin:8px 0 4px}
.plan-price small{font-size:13px;font-weight:500;color:var(--muted)}
.plan-body{padding:18px 20px}
.bullet{list-style:none;padding:0;margin:0;display:grid;gap:8px}
.bullet li{display:flex;gap:8px;align-items:start;font-size:14px;color:var(--ink2)}
.bullet li i{color:var(--ok);margin-top:2px}
.checkout-form{border:1px solid var(--line);border-radius:12px;padding:18px;background:var(--panel)}
.checkout-form h3{font-family:system-ui,sans-serif;font-size:16px;margin:0 0 10px}
.field{display:grid;gap:4px;margin:10px 0}
.field label{font-size:13px;font-weight:600;color:var(--ink)}
.field input, .field select, .field textarea{padding:10px 12px;border:1px solid var(--line);border-radius:8px;background:#fff;font:14px system-ui,sans-serif;width:100%}
.field input:focus, .field textarea:focus{outline:2px solid var(--accent-soft);border-color:var(--accent)}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.status-badge{display:inline-flex;align-items:center;padding:6px 12px;border-radius:999px;font-size:13px;font-weight:700;border:1px solid transparent}
.status-badge.success{background:#e6f4ec;color:#0a5a32;border-color:#c3e6d1}
.status-badge.pending{background:#fff7d6;color:#7a5a00;border-color:#f2e3a3}
.status-badge.cancelled{background:var(--panel);color:var(--ink2);border-color:var(--line)}
.status-badge.failed{background:#fde8e6;color:#8a1f1a;border-color:#f2c1bd}
.faq{display:grid;gap:10px}
.faq-item{border:1px solid var(--line);border-radius:10px;background:#fff}
.faq-item summary{padding:14px 16px;cursor:pointer;font-weight:650;list-style:none;display:flex;justify-content:space-between;align-items:center}
.faq-item summary::-webkit-details-marker{display:none}
.faq-item[open] summary{border-bottom:1px solid var(--line);background:var(--panel)}
.faq-item p{padding:12px 16px;margin:0;color:var(--muted);font-size:14px;line-height:1.6}
.prose{max-width:720px}
.prose p{color:var(--ink2);line-height:1.7}
.site-footer{margin-top:40px;border-top:1px solid var(--line);background:var(--panel);padding:28px 0}
.footer-grid{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr;gap:24px}
@media(max-width:860px){.footer-grid{grid-template-columns:1fr 1fr}}
@media(max-width:520px){.footer-grid{grid-template-columns:1fr}}
.footer-col h4{font-family:system-ui,sans-serif;font-size:13px;letter-spacing:.06em;text-transform:uppercase;color:var(--muted);margin:0 0 10px}
.footer-col a{display:block;padding:4px 0;color:var(--ink2);font-size:14px}
.footer-bottom{margin-top:20px;padding-top:16px;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;font-size:13px;color:var(--muted)}
.auth-section{margin:18px 0;padding:16px;border:1px solid var(--line);border-radius:10px;background:#fff}
#auth-status,#phone-status{margin:8px 0;color:var(--muted);font-size:13px}
table.admin{width:100%;border-collapse:collapse;font-size:13px}
table.admin th{ text-align:left;font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:var(--muted);padding:8px;border-bottom:1px solid var(--line)}
table.admin td{padding:8px;border-bottom:1px solid var(--line)}
article.purchase, article.download{border:1px solid var(--line);border-radius:10px;padding:14px;background:#fff;margin:10px 0}
code{background:var(--panel);padding:2px 6px;border-radius:6px;border:1px solid var(--line);font-size:13px}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}`

const themeScript = `(function(){var k='rm-theme';try{var s=localStorage.getItem(k);var t=s||'light';document.documentElement.setAttribute('data-theme',t);if(!s){try{localStorage.setItem(k,t);}catch(e){}} }catch(e){}document.addEventListener('DOMContentLoaded',function(){var b=document.getElementById('theme-toggle');if(!b)return;b.addEventListener('click',function(){var cur=document.documentElement.getAttribute('data-theme')||'light';var nxt=cur==='light'?'dark':'light';document.documentElement.setAttribute('data-theme',nxt);try{localStorage.setItem(k,nxt);}catch(e){}var toast=document.getElementById('toast');if(toast){toast.textContent=nxt==='dark'?'Dark theme':'Light theme';toast.style.display='block';setTimeout(function(){toast.style.display='none';},1600);}});});})();`

const qolScript = `(function(){function toast(m){var t=document.getElementById('toast');if(!t)return;t.textContent=m;t.style.display='block';clearTimeout(t._h);t._h=setTimeout(function(){t.style.display='none';},2200);}document.addEventListener('click',function(e){var b=e.target.closest('[data-copy]');if(b){var v=b.getAttribute('data-copy');if(!v)return;navigator.clipboard.writeText(v).then(function(){toast('Copied');}).catch(function(){var ta=document.createElement('textarea');ta.value=v;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copied');});}var mb=e.target.closest('#mobile-toggle');if(mb){var nav=document.getElementById('main-nav');if(nav){var isOpen=nav.style.display==='flex';if(window.innerWidth<=860){nav.style.display=isOpen?'none':'flex';nav.style.flexDirection='column';nav.style.position='absolute';nav.style.top='56px';nav.style.insetInlineStart='0';nav.style.insetInlineEnd='0';nav.style.background='var(--panel)';nav.style.padding='12px 24px';nav.style.borderBottom='1px solid var(--line)';}else{nav.style.display='';}} }var ob=e.target.closest('[data-toast]');if(ob){toast(ob.getAttribute('data-toast'));}});document.addEventListener('keydown',function(e){if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();var s=document.querySelector('input[name="q"]');if(s){s.focus();toast('Search focused');}}});})();`

// csrfInput helper kept for compatibility with non-templ paths.
func csrfInput(token string) template.HTML {
	return template.HTML(`<input type="hidden" name="csrf_token" value="` + template.HTMLEscapeString(token) + `">`)
}

var _ = templruntime.GeneratedTemplate
